//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSProjectRibbon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Actual
    {
        public int id { get; set; }
        public string job { get; set; }
        public Nullable<System.DateTime> designstart { get; set; }
        public Nullable<System.DateTime> designend { get; set; }
        public Nullable<System.DateTime> processingstart { get; set; }
        public Nullable<System.DateTime> processingend { get; set; }
        public Nullable<System.DateTime> weldstart { get; set; }
        public Nullable<System.DateTime> weldend { get; set; }
        public Nullable<System.DateTime> machinestart { get; set; }
        public Nullable<System.DateTime> machineend { get; set; }
        public Nullable<System.DateTime> assemblystart { get; set; }
        public Nullable<System.DateTime> assemblyend { get; set; }
        public Nullable<System.DateTime> qastart { get; set; }
        public Nullable<System.DateTime> qaend { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> materialstart { get; set; }
        public Nullable<System.DateTime> materialend { get; set; }
    }
}
