//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualsRep
    {
        public string BaseID { get; set; }
        public string Design { get; set; }
        public string Planning { get; set; }
        public string Waterjet { get; set; }
        public string Weld { get; set; }
        public string Nc { get; set; }
        public string Machining { get; set; }
        public string Assy { get; set; }
        public string Inspection { get; set; }
        public Nullable<decimal> ServiceCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> BurdenCost { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> DesignCost { get; set; }
        public Nullable<decimal> PlanningCost { get; set; }
        public Nullable<decimal> WaterJetCost { get; set; }
        public Nullable<decimal> WeldCost { get; set; }
        public Nullable<decimal> NcCost { get; set; }
        public Nullable<decimal> MachiningCost { get; set; }
        public Nullable<decimal> AssyCost { get; set; }
        public Nullable<decimal> InspectionCost { get; set; }
    }
}
