//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adoEntities : DbContext
    {
        public adoEntities()
            : base("name=adoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobMetric> JobMetrics { get; set; }
        public virtual DbSet<JobHour> JobHours { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<ActualsRep> ActualsReps { get; set; }
        public virtual DbSet<Kickoff> Kickoffs { get; set; }
    }
}
