//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kickoff
    {
        public int id { get; set; }
        public Nullable<int> Planning { get; set; }
        public Nullable<int> Design { get; set; }
        public Nullable<int> Waterjet { get; set; }
        public Nullable<int> Weld { get; set; }
        public Nullable<int> NC { get; set; }
        public Nullable<int> Convetional { get; set; }
        public Nullable<decimal> Outsource { get; set; }
        public Nullable<int> Assy { get; set; }
        public Nullable<int> Inspection { get; set; }
        public Nullable<int> Shipping { get; set; }
        public Nullable<int> PlanningEst { get; set; }
        public Nullable<int> DesignEst { get; set; }
        public Nullable<int> WaterjetEst { get; set; }
        public Nullable<int> WeldEst { get; set; }
        public Nullable<int> NCEst { get; set; }
        public Nullable<int> ConventionalEst { get; set; }
        public Nullable<int> OutsourceEst { get; set; }
        public Nullable<int> AssemblyEst { get; set; }
        public Nullable<int> InspectionEst { get; set; }
        public Nullable<int> ShippingEst { get; set; }
        public string BaseID { get; set; }
    }
}
