//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionItem
    {
        public int ID { get; set; }
        public string Submitter { get; set; }
        public string Asignee { get; set; }
        public string Base { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public string critical { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ActionRequired { get; set; }
        public string openitem { get; set; }
    
        public virtual ActionItem ActionItems1 { get; set; }
        public virtual ActionItem ActionItem1 { get; set; }
    }
}
