//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public string JobNumber { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> PMFolder { get; set; }
        public Nullable<System.DateTime> WeldFolder { get; set; }
        public Nullable<System.DateTime> MachineFolder { get; set; }
        public Nullable<System.DateTime> BuildFolder { get; set; }
        public Nullable<System.DateTime> ProcessingFolder { get; set; }
    }
}
