//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantDate
    {
        public string BaseID { get; set; }
        public Nullable<System.DateTime> RecvMaterial { get; set; }
        public Nullable<System.DateTime> StartFab { get; set; }
        public Nullable<System.DateTime> HeatTreat { get; set; }
        public Nullable<System.DateTime> StartMachining { get; set; }
        public Nullable<System.DateTime> StartAssy { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> MachComp { get; set; }
        public Nullable<System.DateTime> RdyChk { get; set; }
        public Nullable<System.DateTime> RdySrc { get; set; }
        public Nullable<System.DateTime> DesRel { get; set; }
    }
}
