//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_batches
    {
        public Nullable<System.DateTime> BatchDate { get; set; }
        public int Batch { get; set; }
        public Nullable<int> Weld { get; set; }
        public Nullable<int> Machine { get; set; }
        public Nullable<int> Build { get; set; }
        public Nullable<int> Tracker { get; set; }
        public Nullable<int> Design { get; set; }
        public string BaseID { get; set; }
    }
}
