//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobMetric
    {
        public string BaseID { get; set; }
        public Nullable<decimal> Comp { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> POValue { get; set; }
        public Nullable<decimal> Actual { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public int batch { get; set; }
        public string ShipMonth { get; set; }
        public Nullable<decimal> RemainingRev { get; set; }
        public Nullable<decimal> Projected { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
    }
}
