//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin_Over_time
    {
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string BaseID { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
    }
}
