//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduling
    {
        public Nullable<System.DateTime> DataHold { get; set; }
        public Nullable<System.DateTime> StartFab { get; set; }
        public Nullable<System.DateTime> FinishFab { get; set; }
        public Nullable<System.DateTime> StartHeat { get; set; }
        public Nullable<System.DateTime> FinishHeat { get; set; }
        public Nullable<System.DateTime> StartMach3 { get; set; }
        public Nullable<System.DateTime> FinishMach3 { get; set; }
        public Nullable<System.DateTime> StartMach5 { get; set; }
        public Nullable<System.DateTime> FinishMach5 { get; set; }
        public Nullable<System.DateTime> StartAssembly { get; set; }
        public Nullable<System.DateTime> FinishAsssembly { get; set; }
        public Nullable<System.DateTime> StartMachSmall { get; set; }
        public Nullable<System.DateTime> FinishMachSmall { get; set; }
        public Nullable<System.DateTime> StartMaterial { get; set; }
        public Nullable<System.DateTime> FinishMaterial { get; set; }
        public Nullable<System.DateTime> StartBench { get; set; }
        public Nullable<System.DateTime> FinishBench { get; set; }
        public Nullable<System.DateTime> StartPaint { get; set; }
        public Nullable<System.DateTime> FinishPaint { get; set; }
        public Nullable<System.DateTime> StartTracker { get; set; }
        public Nullable<System.DateTime> FinishTracker { get; set; }
        public Nullable<System.DateTime> StartQa { get; set; }
        public Nullable<System.DateTime> FinishQa { get; set; }
        public Nullable<System.DateTime> StartSts { get; set; }
        public Nullable<System.DateTime> FinishSts { get; set; }
        public Nullable<System.DateTime> StartCommercial { get; set; }
        public Nullable<System.DateTime> FinishCommercial { get; set; }
        public Nullable<System.DateTime> StartDesign { get; set; }
        public Nullable<System.DateTime> FinishDesign { get; set; }
        public Nullable<System.DateTime> DesignRelease { get; set; }
        public string Base_ID { get; set; }
        public Nullable<System.DateTime> StartFinalize { get; set; }
        public Nullable<System.DateTime> FinishFinalize { get; set; }
    }
}
