//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDirect
    {
        public int id { get; set; }
        public string FOB { get; set; }
        public string PrimaryCommodity { get; set; }
        public string SecondaryCommodity { get; set; }
        public string AS9100Registration { get; set; }
        public Nullable<System.DateTime> ASExpiration { get; set; }
        public string ASDocument { get; set; }
        public string IsoRegistration { get; set; }
        public Nullable<System.DateTime> IsoExpiration { get; set; }
        public string IsoDocument { get; set; }
        public string OtherRegistration { get; set; }
        public Nullable<System.DateTime> OtherExpiration { get; set; }
        public string OtherDocument { get; set; }
        public string ItarApproved { get; set; }
        public Nullable<System.DateTime> ItarExpiration { get; set; }
        public string ItarDocument { get; set; }
        public string DPDApproval { get; set; }
        public string SpecialProcesses { get; set; }
        public string SpecialProcessDetail { get; set; }
        public string ShipVia { get; set; }
        public string Name { get; set; }
    }
}
