//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRedTag
    {
        public int ID { get; set; }
        public string JOB { get; set; }
        public string Detail { get; set; }
        public string Initiator { get; set; }
        public string Dept { get; set; }
        public string Spec { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Defect { get; set; }
        public string Cause { get; set; }
        public string Instructions { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Reinspection { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> InstanceCost { get; set; }
        public Nullable<int> ScrapCost { get; set; }
        public string CAR { get; set; }
        public string VendorPO { get; set; }
        public string Disposition { get; set; }
    }
}
