//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public string JobNumber { get; set; }
        public string ProgramManager { get; set; }
        public string BuildLeader { get; set; }
        public string Processor { get; set; }
        public Nullable<System.DateTime> KickOff { get; set; }
        public Nullable<System.DateTime> DataRelease { get; set; }
        public Nullable<System.DateTime> Folder { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
    }
}
