//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WipViewer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionItem> ActionItems { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<ImportantDate> ImportantDates { get; set; }
        public virtual DbSet<JobHour> JobHours { get; set; }
        public virtual DbSet<JobMetric> JobMetrics { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ActiveJob> ActiveJobs { get; set; }
        public virtual DbSet<Job_batches> Job_batches { get; set; }
        public virtual DbSet<Margin_Over_time> Margin_Over_time { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<BondActual> BondActuals { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<tblRedTag> tblRedTags { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Scheduling> Schedulings { get; set; }
    }
}
